services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      - APP_URL=http://localhost:3000
      - KC_DB=postgres
      - KC_DB_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://keycloak-postgres/keycloak
      - KC_DB_USERNAME=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_REALM=webapp
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    depends_on:
      - keycloak-postgres
    ports:
      - "8080:8080"
      - "8787:8787"
    command:
      - start-dev
      - --features=admin-fine-grained-authz
      - --import-realm
      - --proxy-headers=forwarded
    networks:
      - appnet

  keycloak-postgres:
    image: postgres:16
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "keycloak", "-U", "admin"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=keycloak
    ports:
      - "5432:5432"
    networks:
      - appnet

  authjs-docker-test:
    build:
      context: ./nextjs-auth-example
      dockerfile: Dockerfile
    environment:
      - AUTH_KEYCLOAK_ID=webapp
      - AUTH_KEYCLOAK_ISSUER=http://localhost:8080/realms/webapp
      - AUTH_KEYCLOAK_SECRET="gfF0OCkYoAfyCph4Mv4LLytkuzKoEJNG"
      - AUTH_SECRET="MohY0/2zSQw/psWEnejC2ka3Al0oifvY4YjOkUaFfnI="
      - AUTH_URL=http://localhost:3000/auth
    ports:
      - "3000:3000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
